---
title: "Enunciados"
author: "Nicolás González García"
date: "`r Sys.Date()`"
output: pdf_document
---

## ACTIVIDAD 1
Aplicar los criterios de decisión bajo incertidumbre a los problemas cuya matriz de valores viene dada e la tabla siguiente.  
Considerar beneficios (favorable) y costos (desfavorable)  

```{r echo=FALSE}
source("teoriadecision_funciones_incertidumbre.R")
m1A <- crea.tablaX(c(7,5,1,
                     -3,1,3,
                     5,-1,3,
                     5,4,-10),
                   numalternativas = 4, numestados = 3)
m1A
```

## ACTIVIDAD 2

**Elección de un Transporte para el Trabajo**

Nico está considerando sus opciones de transporte para ir al trabajo. Tiene tres alternativas:

1. **Conducir su propio automóvil:** Nico puede conducir su automóvil al trabajo. El costo mensual de gasolina y estacionamiento es de 200. Además, hay una pequeña probabilidad de sufrir una multa de estacionamiento de 50 por mes.

2. **Tomar el transporte público:** Nico puede optar por usar el transporte público para ir al trabajo. El costo mensual del pase de transporte público es de 80. Sin embargo, ocasionalmente, el transporte público puede tener retrasos, lo que resulta en llegar tarde al trabajo, lo que le cuesta 30 adicionales en promedio por mes en tiempo perdido.

3. **Compartir con un colega:** Nico tiene un colega con el que puede hacer carpooling. Compartir el automóvil con su colega reduce su costo de gasolina y estacionamiento a 120 por mes. También disminuye la probabilidad de multa de estacionamiento a la mitad, es decir, 25 por mes. Sin embargo, si su colega no está disponible, Nico debe conducir solo y pagar el costo normal de 200.

Nico tiene dos estados de la naturaleza para considerar:

**Estado de la Naturaleza 1: Disponibilidad del Colega:** En este estado, su colega está disponible para compartir el viaje en carpooling.

**Estado de la Naturaleza 2: Indisponibilidad del Colega:** En este estado, su colega no puede compartir el viaje en carpooling.

¿Cuál es la opción más conveniente para Nico en términos de costo total durante el primer año? Representa las ecuaciones de alternativas para cada opción de transporte y estado de la naturaleza